//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// Defines values for ConfigUpdateRequestStrategyName.
const (
	Scalping ConfigUpdateRequestStrategyName = "scalping"
	Simple   ConfigUpdateRequestStrategyName = "simple"
)

// Valid indicates whether the value is a known member of the ConfigUpdateRequestStrategyName enum.
func (e ConfigUpdateRequestStrategyName) Valid() bool {
	switch e {
	case Scalping:
		return true
	case Simple:
		return true
	default:
		return false
	}
}

// Defines values for LogEntryCategory.
const (
	LogEntryCategoryApi      LogEntryCategory = "api"
	LogEntryCategoryData     LogEntryCategory = "data"
	LogEntryCategoryStrategy LogEntryCategory = "strategy"
	LogEntryCategorySystem   LogEntryCategory = "system"
	LogEntryCategoryTrading  LogEntryCategory = "trading"
	LogEntryCategoryUi       LogEntryCategory = "ui"
)

// Valid indicates whether the value is a known member of the LogEntryCategory enum.
func (e LogEntryCategory) Valid() bool {
	switch e {
	case LogEntryCategoryApi:
		return true
	case LogEntryCategoryData:
		return true
	case LogEntryCategoryStrategy:
		return true
	case LogEntryCategorySystem:
		return true
	case LogEntryCategoryTrading:
		return true
	case LogEntryCategoryUi:
		return true
	default:
		return false
	}
}

// Defines values for LogEntryLevel.
const (
	LogEntryLevelDEBUG LogEntryLevel = "DEBUG"
	LogEntryLevelERROR LogEntryLevel = "ERROR"
	LogEntryLevelINFO  LogEntryLevel = "INFO"
	LogEntryLevelWARN  LogEntryLevel = "WARN"
)

// Valid indicates whether the value is a known member of the LogEntryLevel enum.
func (e LogEntryLevel) Valid() bool {
	switch e {
	case LogEntryLevelDEBUG:
		return true
	case LogEntryLevelERROR:
		return true
	case LogEntryLevelINFO:
		return true
	case LogEntryLevelWARN:
		return true
	default:
		return false
	}
}

// Defines values for OrderResponseSide.
const (
	OrderResponseSideBUY  OrderResponseSide = "BUY"
	OrderResponseSideSELL OrderResponseSide = "SELL"
)

// Valid indicates whether the value is a known member of the OrderResponseSide enum.
func (e OrderResponseSide) Valid() bool {
	switch e {
	case OrderResponseSideBUY:
		return true
	case OrderResponseSideSELL:
		return true
	default:
		return false
	}
}

// Defines values for OrderResponseStatus.
const (
	OrderResponseStatusACTIVE    OrderResponseStatus = "ACTIVE"
	OrderResponseStatusCANCELED  OrderResponseStatus = "CANCELED"
	OrderResponseStatusCOMPLETED OrderResponseStatus = "COMPLETED"
	OrderResponseStatusEXPIRED   OrderResponseStatus = "EXPIRED"
	OrderResponseStatusREJECTED  OrderResponseStatus = "REJECTED"
)

// Valid indicates whether the value is a known member of the OrderResponseStatus enum.
func (e OrderResponseStatus) Valid() bool {
	switch e {
	case OrderResponseStatusACTIVE:
		return true
	case OrderResponseStatusCANCELED:
		return true
	case OrderResponseStatusCOMPLETED:
		return true
	case OrderResponseStatusEXPIRED:
		return true
	case OrderResponseStatusREJECTED:
		return true
	default:
		return false
	}
}

// Defines values for TradeSide.
const (
	TradeSideBUY  TradeSide = "BUY"
	TradeSideSELL TradeSide = "SELL"
)

// Valid indicates whether the value is a known member of the TradeSide enum.
func (e TradeSide) Valid() bool {
	switch e {
	case TradeSideBUY:
		return true
	case TradeSideSELL:
		return true
	default:
		return false
	}
}

// Defines values for TradeStatus.
const (
	TradeStatusACTIVE    TradeStatus = "ACTIVE"
	TradeStatusCANCELED  TradeStatus = "CANCELED"
	TradeStatusCOMPLETED TradeStatus = "COMPLETED"
	TradeStatusEXPIRED   TradeStatus = "EXPIRED"
	TradeStatusREJECTED  TradeStatus = "REJECTED"
)

// Valid indicates whether the value is a known member of the TradeStatus enum.
func (e TradeStatus) Valid() bool {
	switch e {
	case TradeStatusACTIVE:
		return true
	case TradeStatusCANCELED:
		return true
	case TradeStatusCOMPLETED:
		return true
	case TradeStatusEXPIRED:
		return true
	case TradeStatusREJECTED:
		return true
	default:
		return false
	}
}

// Defines values for TradingStatusResponseStatus.
const (
	Error   TradingStatusResponseStatus = "error"
	Running TradingStatusResponseStatus = "running"
	Stopped TradingStatusResponseStatus = "stopped"
	Success TradingStatusResponseStatus = "success"
)

// Valid indicates whether the value is a known member of the TradingStatusResponseStatus enum.
func (e TradingStatusResponseStatus) Valid() bool {
	switch e {
	case Error:
		return true
	case Running:
		return true
	case Stopped:
		return true
	case Success:
		return true
	default:
		return false
	}
}

// Defines values for GetApiLogsParamsLevel.
const (
	GetApiLogsParamsLevelDEBUG GetApiLogsParamsLevel = "DEBUG"
	GetApiLogsParamsLevelERROR GetApiLogsParamsLevel = "ERROR"
	GetApiLogsParamsLevelINFO  GetApiLogsParamsLevel = "INFO"
	GetApiLogsParamsLevelWARN  GetApiLogsParamsLevel = "WARN"
)

// Valid indicates whether the value is a known member of the GetApiLogsParamsLevel enum.
func (e GetApiLogsParamsLevel) Valid() bool {
	switch e {
	case GetApiLogsParamsLevelDEBUG:
		return true
	case GetApiLogsParamsLevelERROR:
		return true
	case GetApiLogsParamsLevelINFO:
		return true
	case GetApiLogsParamsLevelWARN:
		return true
	default:
		return false
	}
}

// Defines values for GetApiLogsParamsCategory.
const (
	GetApiLogsParamsCategoryApi      GetApiLogsParamsCategory = "api"
	GetApiLogsParamsCategoryData     GetApiLogsParamsCategory = "data"
	GetApiLogsParamsCategoryStrategy GetApiLogsParamsCategory = "strategy"
	GetApiLogsParamsCategorySystem   GetApiLogsParamsCategory = "system"
	GetApiLogsParamsCategoryTrading  GetApiLogsParamsCategory = "trading"
	GetApiLogsParamsCategoryUi       GetApiLogsParamsCategory = "ui"
)

// Valid indicates whether the value is a known member of the GetApiLogsParamsCategory enum.
func (e GetApiLogsParamsCategory) Valid() bool {
	switch e {
	case GetApiLogsParamsCategoryApi:
		return true
	case GetApiLogsParamsCategoryData:
		return true
	case GetApiLogsParamsCategoryStrategy:
		return true
	case GetApiLogsParamsCategorySystem:
		return true
	case GetApiLogsParamsCategoryTrading:
		return true
	case GetApiLogsParamsCategoryUi:
		return true
	default:
		return false
	}
}

// Balance defines model for Balance.
type Balance struct {
	Amount    *float32   `json:"amount,omitempty"`
	Available *float32   `json:"available,omitempty"`
	Currency  *string    `json:"currency,omitempty"`
	Id        *int       `json:"id,omitempty"`
	Timestamp *time.Time `json:"timestamp,omitempty"`
}

// Config アプリケーション設定全体。詳細は docs/CONFIG.md を参照。
type Config struct {
	StrategyParams *map[string]interface{} `json:"strategy_params,omitempty"`
	Trading        *struct {
		Strategy *struct {
			Name *string `json:"name,omitempty"`
		} `json:"strategy,omitempty"`
	} `json:"trading,omitempty"`
}

// ConfigUpdateRequest defines model for ConfigUpdateRequest.
type ConfigUpdateRequest struct {
	Risk *struct {
		// StopLoss 損切パーセント（0〜100）
		StopLoss *float32 `json:"stop_loss,omitempty"`

		// TakeProfit 利確パーセント（0〜100）
		TakeProfit *float32 `json:"take_profit,omitempty"`
	} `json:"risk,omitempty"`
	Strategy *struct {
		Name *ConfigUpdateRequestStrategyName `json:"name,omitempty"`
	} `json:"strategy,omitempty"`
}

// ConfigUpdateRequestStrategyName defines model for ConfigUpdateRequest.Strategy.Name.
type ConfigUpdateRequestStrategyName string

// ConfigUpdateResponse defines model for ConfigUpdateResponse.
type ConfigUpdateResponse struct {
	// Config アプリケーション設定全体。詳細は docs/CONFIG.md を参照。
	Config  *Config `json:"config,omitempty"`
	Message *string `json:"message,omitempty"`
	Status  *string `json:"status,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Message *string `json:"message,omitempty"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status    *string    `json:"status,omitempty"`
	Timestamp *time.Time `json:"timestamp,omitempty"`
	Uptime    *string    `json:"uptime,omitempty"`
	Version   *string    `json:"version,omitempty"`
}

// LogEntry defines model for LogEntry.
type LogEntry struct {
	Category  *LogEntryCategory       `json:"category,omitempty"`
	Fields    *map[string]interface{} `json:"fields,omitempty"`
	Level     *LogEntryLevel          `json:"level,omitempty"`
	Message   *string                 `json:"message,omitempty"`
	Timestamp *time.Time              `json:"timestamp,omitempty"`
}

// LogEntryCategory defines model for LogEntry.Category.
type LogEntryCategory string

// LogEntryLevel defines model for LogEntry.Level.
type LogEntryLevel string

// OrderResponse defines model for OrderResponse.
type OrderResponse struct {
	CreatedAt  *time.Time           `json:"created_at,omitempty"`
	ExecutedAt *time.Time           `json:"executed_at,omitempty"`
	OrderId    *string              `json:"order_id,omitempty"`
	Price      *float32             `json:"price,omitempty"`
	Side       *OrderResponseSide   `json:"side,omitempty"`
	Size       *float32             `json:"size,omitempty"`
	Status     *OrderResponseStatus `json:"status,omitempty"`
	Symbol     *string              `json:"symbol,omitempty"`
	Type       *string              `json:"type,omitempty"`
}

// OrderResponseSide defines model for OrderResponse.Side.
type OrderResponseSide string

// OrderResponseStatus defines model for OrderResponse.Status.
type OrderResponseStatus string

// PerformanceMetric defines model for PerformanceMetric.
type PerformanceMetric struct {
	AverageLoss     *float32   `json:"average_loss,omitempty"`
	AverageWin      *float32   `json:"average_win,omitempty"`
	ConsecutiveLoss *int       `json:"consecutive_loss,omitempty"`
	ConsecutiveWins *int       `json:"consecutive_wins,omitempty"`
	DailyReturn     *float32   `json:"daily_return,omitempty"`
	Date            *time.Time `json:"date,omitempty"`
	Id              *int       `json:"id,omitempty"`
	LargestLoss     *float32   `json:"largest_loss,omitempty"`
	LargestWin      *float32   `json:"largest_win,omitempty"`
	LosingTrades    *int       `json:"losing_trades,omitempty"`
	MaxDrawdown     *float32   `json:"max_drawdown,omitempty"`
	ProfitFactor    *float32   `json:"profit_factor,omitempty"`
	SharpeRatio     *float32   `json:"sharpe_ratio,omitempty"`
	TotalPnl        *float32   `json:"total_pnl,omitempty"`
	TotalReturn     *float32   `json:"total_return,omitempty"`
	TotalTrades     *int       `json:"total_trades,omitempty"`

	// WinRate 勝率（0.0 〜 1.0）
	WinRate       *float32 `json:"win_rate,omitempty"`
	WinningTrades *int     `json:"winning_trades,omitempty"`
}

// SimpleSuccess defines model for SimpleSuccess.
type SimpleSuccess struct {
	Message *string `json:"message,omitempty"`
	Status  *string `json:"status,omitempty"`
}

// StatusResponse defines model for StatusResponse.
type StatusResponse struct {
	ActiveOrders      *int                `json:"active_orders,omitempty"`
	CredentialsStatus *string             `json:"credentials_status,omitempty"`
	CurrentPrice      *float32            `json:"current_price,omitempty"`
	CurrentSignal     *string             `json:"current_signal,omitempty"`
	LastUpdate        *time.Time          `json:"last_update,omitempty"`
	MonitoringPrices  *map[string]float32 `json:"monitoring_prices,omitempty"`
	MonitoringSymbols *[]string           `json:"monitoring_symbols,omitempty"`
	Status            *string             `json:"status,omitempty"`
	Strategy          *string             `json:"strategy,omitempty"`
	TotalTrades       *int                `json:"total_trades,omitempty"`
	TradingEnabled    *bool               `json:"trading_enabled,omitempty"`
	Uptime            *string             `json:"uptime,omitempty"`
}

// Trade defines model for Trade.
type Trade struct {
	Amount       *float32     `json:"amount,omitempty"`
	CreatedAt    *time.Time   `json:"created_at,omitempty"`
	ExecutedAt   *time.Time   `json:"executed_at,omitempty"`
	Fee          *float32     `json:"fee,omitempty"`
	Id           *int         `json:"id,omitempty"`
	OrderId      *string      `json:"order_id,omitempty"`
	Pnl          *float32     `json:"pnl,omitempty"`
	Price        *float32     `json:"price,omitempty"`
	ProductCode  *string      `json:"product_code,omitempty"`
	Side         *TradeSide   `json:"side,omitempty"`
	Size         *float32     `json:"size,omitempty"`
	Status       *TradeStatus `json:"status,omitempty"`
	StrategyName *string      `json:"strategy_name,omitempty"`
	Symbol       *string      `json:"symbol,omitempty"`
	Type         *string      `json:"type,omitempty"`
	UpdatedAt    *time.Time   `json:"updated_at,omitempty"`
}

// TradeSide defines model for Trade.Side.
type TradeSide string

// TradeStatus defines model for Trade.Status.
type TradeStatus string

// TradingStatusResponse defines model for TradingStatusResponse.
type TradingStatusResponse struct {
	Enabled   *bool                        `json:"enabled,omitempty"`
	Message   *string                      `json:"message,omitempty"`
	Status    *TradingStatusResponseStatus `json:"status,omitempty"`
	Timestamp *time.Time                   `json:"timestamp,omitempty"`
}

// TradingStatusResponseStatus defines model for TradingStatusResponse.Status.
type TradingStatusResponseStatus string

// LimitParam defines model for LimitParam.
type LimitParam = int

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// InternalServerError defines model for InternalServerError.
type InternalServerError = ErrorResponse

// ServiceUnavailable defines model for ServiceUnavailable.
type ServiceUnavailable = ErrorResponse

// GetApiLogsParams defines parameters for GetApiLogs.
type GetApiLogsParams struct {
	// Limit 取得件数（デフォルト: 100、最大: 1000）
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Level ログレベルフィルター
	Level *GetApiLogsParamsLevel `form:"level,omitempty" json:"level,omitempty"`

	// Category カテゴリフィルター
	Category *GetApiLogsParamsCategory `form:"category,omitempty" json:"category,omitempty"`
}

// GetApiLogsParamsLevel defines parameters for GetApiLogs.
type GetApiLogsParamsLevel string

// GetApiLogsParamsCategory defines parameters for GetApiLogs.
type GetApiLogsParamsCategory string

// GetApiOrdersParams defines parameters for GetApiOrders.
type GetApiOrdersParams struct {
	// Limit 取得件数（デフォルト: 20、最大: 100）
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetApiStatusParams defines parameters for GetApiStatus.
type GetApiStatusParams struct {
	// Symbol 価格取得対象のシンボル（省略時は設定の第一シンボル）
	Symbol *string `form:"symbol,omitempty" json:"symbol,omitempty"`
}

// GetApiTradesParams defines parameters for GetApiTrades.
type GetApiTradesParams struct {
	// Limit 取得件数（デフォルト: 50）
	Limit *LimitParam `form:"limit,omitempty" json:"limit,omitempty"`
}

// PostApiConfigJSONRequestBody defines body for PostApiConfig for application/json ContentType.
type PostApiConfigJSONRequestBody = ConfigUpdateRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// 残高取得
	// (GET /api/balance)
	GetApiBalance(w http.ResponseWriter, r *http.Request)
	// 現在の設定を取得
	// (GET /api/config)
	GetApiConfig(w http.ResponseWriter, r *http.Request)
	// 設定を更新
	// (POST /api/config)
	PostApiConfig(w http.ResponseWriter, r *http.Request)
	// ログの取得
	// (GET /api/logs)
	GetApiLogs(w http.ResponseWriter, r *http.Request, params GetApiLogsParams)
	// 注文履歴の取得
	// (GET /api/orders)
	GetApiOrders(w http.ResponseWriter, r *http.Request, params GetApiOrdersParams)
	// パフォーマンス指標の取得
	// (GET /api/performance)
	GetApiPerformance(w http.ResponseWriter, r *http.Request)
	// システム状態の取得
	// (GET /api/status)
	GetApiStatus(w http.ResponseWriter, r *http.Request, params GetApiStatusParams)
	// 戦略状態のリセット
	// (POST /api/strategy/reset)
	PostApiStrategyReset(w http.ResponseWriter, r *http.Request)
	// 取引履歴の取得
	// (GET /api/trades)
	GetApiTrades(w http.ResponseWriter, r *http.Request, params GetApiTradesParams)
	// 取引開始
	// (POST /api/trading/start)
	PostApiTradingStart(w http.ResponseWriter, r *http.Request)
	// 取引状態の取得
	// (GET /api/trading/status)
	GetApiTradingStatus(w http.ResponseWriter, r *http.Request)
	// 取引停止
	// (POST /api/trading/stop)
	PostApiTradingStop(w http.ResponseWriter, r *http.Request)
	// ヘルスチェック
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetApiBalance operation middleware
func (siw *ServerInterfaceWrapper) GetApiBalance(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiBalance(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiConfig operation middleware
func (siw *ServerInterfaceWrapper) GetApiConfig(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiConfig(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiConfig operation middleware
func (siw *ServerInterfaceWrapper) PostApiConfig(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiConfig(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiLogs operation middleware
func (siw *ServerInterfaceWrapper) GetApiLogs(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiLogsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "level" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "level", r.URL.Query(), &params.Level, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "level", Err: err})
		return
	}

	// ------------- Optional query parameter "category" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "category", r.URL.Query(), &params.Category, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "category", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiLogs(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiOrders operation middleware
func (siw *ServerInterfaceWrapper) GetApiOrders(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiOrdersParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiOrders(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiPerformance operation middleware
func (siw *ServerInterfaceWrapper) GetApiPerformance(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiPerformance(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiStatus operation middleware
func (siw *ServerInterfaceWrapper) GetApiStatus(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiStatusParams

	// ------------- Optional query parameter "symbol" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "symbol", r.URL.Query(), &params.Symbol, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "symbol", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiStatus(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiStrategyReset operation middleware
func (siw *ServerInterfaceWrapper) PostApiStrategyReset(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiStrategyReset(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiTrades operation middleware
func (siw *ServerInterfaceWrapper) GetApiTrades(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiTradesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiTrades(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiTradingStart operation middleware
func (siw *ServerInterfaceWrapper) PostApiTradingStart(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiTradingStart(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiTradingStatus operation middleware
func (siw *ServerInterfaceWrapper) GetApiTradingStatus(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiTradingStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiTradingStop operation middleware
func (siw *ServerInterfaceWrapper) PostApiTradingStop(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiTradingStop(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/api/balance", wrapper.GetApiBalance)
	m.HandleFunc("GET "+options.BaseURL+"/api/config", wrapper.GetApiConfig)
	m.HandleFunc("POST "+options.BaseURL+"/api/config", wrapper.PostApiConfig)
	m.HandleFunc("GET "+options.BaseURL+"/api/logs", wrapper.GetApiLogs)
	m.HandleFunc("GET "+options.BaseURL+"/api/orders", wrapper.GetApiOrders)
	m.HandleFunc("GET "+options.BaseURL+"/api/performance", wrapper.GetApiPerformance)
	m.HandleFunc("GET "+options.BaseURL+"/api/status", wrapper.GetApiStatus)
	m.HandleFunc("POST "+options.BaseURL+"/api/strategy/reset", wrapper.PostApiStrategyReset)
	m.HandleFunc("GET "+options.BaseURL+"/api/trades", wrapper.GetApiTrades)
	m.HandleFunc("POST "+options.BaseURL+"/api/trading/start", wrapper.PostApiTradingStart)
	m.HandleFunc("GET "+options.BaseURL+"/api/trading/status", wrapper.GetApiTradingStatus)
	m.HandleFunc("POST "+options.BaseURL+"/api/trading/stop", wrapper.PostApiTradingStop)
	m.HandleFunc("GET "+options.BaseURL+"/health", wrapper.GetHealth)

	return m
}

type BadRequestJSONResponse ErrorResponse

type InternalServerErrorJSONResponse ErrorResponse

type ServiceUnavailableJSONResponse ErrorResponse

type GetApiBalanceRequestObject struct {
}

type GetApiBalanceResponseObject interface {
	VisitGetApiBalanceResponse(w http.ResponseWriter) error
}

type GetApiBalance200JSONResponse []Balance

func (response GetApiBalance200JSONResponse) VisitGetApiBalanceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetApiBalance500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetApiBalance500JSONResponse) VisitGetApiBalanceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetApiConfigRequestObject struct {
}

type GetApiConfigResponseObject interface {
	VisitGetApiConfigResponse(w http.ResponseWriter) error
}

type GetApiConfig200JSONResponse Config

func (response GetApiConfig200JSONResponse) VisitGetApiConfigResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostApiConfigRequestObject struct {
	Body *PostApiConfigJSONRequestBody
}

type PostApiConfigResponseObject interface {
	VisitPostApiConfigResponse(w http.ResponseWriter) error
}

type PostApiConfig200JSONResponse ConfigUpdateResponse

func (response PostApiConfig200JSONResponse) VisitPostApiConfigResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostApiConfig400JSONResponse struct{ BadRequestJSONResponse }

func (response PostApiConfig400JSONResponse) VisitPostApiConfigResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostApiConfig500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response PostApiConfig500JSONResponse) VisitPostApiConfigResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetApiLogsRequestObject struct {
	Params GetApiLogsParams
}

type GetApiLogsResponseObject interface {
	VisitGetApiLogsResponse(w http.ResponseWriter) error
}

type GetApiLogs200JSONResponse []LogEntry

func (response GetApiLogs200JSONResponse) VisitGetApiLogsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetApiLogs400JSONResponse struct{ BadRequestJSONResponse }

func (response GetApiLogs400JSONResponse) VisitGetApiLogsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetApiLogs500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetApiLogs500JSONResponse) VisitGetApiLogsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetApiOrdersRequestObject struct {
	Params GetApiOrdersParams
}

type GetApiOrdersResponseObject interface {
	VisitGetApiOrdersResponse(w http.ResponseWriter) error
}

type GetApiOrders200JSONResponse []OrderResponse

func (response GetApiOrders200JSONResponse) VisitGetApiOrdersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetApiOrders400JSONResponse struct{ BadRequestJSONResponse }

func (response GetApiOrders400JSONResponse) VisitGetApiOrdersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetApiOrders500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetApiOrders500JSONResponse) VisitGetApiOrdersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetApiPerformanceRequestObject struct {
}

type GetApiPerformanceResponseObject interface {
	VisitGetApiPerformanceResponse(w http.ResponseWriter) error
}

type GetApiPerformance200JSONResponse []PerformanceMetric

func (response GetApiPerformance200JSONResponse) VisitGetApiPerformanceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetApiPerformance500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetApiPerformance500JSONResponse) VisitGetApiPerformanceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetApiStatusRequestObject struct {
	Params GetApiStatusParams
}

type GetApiStatusResponseObject interface {
	VisitGetApiStatusResponse(w http.ResponseWriter) error
}

type GetApiStatus200JSONResponse StatusResponse

func (response GetApiStatus200JSONResponse) VisitGetApiStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostApiStrategyResetRequestObject struct {
}

type PostApiStrategyResetResponseObject interface {
	VisitPostApiStrategyResetResponse(w http.ResponseWriter) error
}

type PostApiStrategyReset200JSONResponse SimpleSuccess

func (response PostApiStrategyReset200JSONResponse) VisitPostApiStrategyResetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostApiStrategyReset500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response PostApiStrategyReset500JSONResponse) VisitPostApiStrategyResetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostApiStrategyReset503JSONResponse struct{ ServiceUnavailableJSONResponse }

func (response PostApiStrategyReset503JSONResponse) VisitPostApiStrategyResetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type GetApiTradesRequestObject struct {
	Params GetApiTradesParams
}

type GetApiTradesResponseObject interface {
	VisitGetApiTradesResponse(w http.ResponseWriter) error
}

type GetApiTrades200JSONResponse []Trade

func (response GetApiTrades200JSONResponse) VisitGetApiTradesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetApiTrades500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetApiTrades500JSONResponse) VisitGetApiTradesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostApiTradingStartRequestObject struct {
}

type PostApiTradingStartResponseObject interface {
	VisitPostApiTradingStartResponse(w http.ResponseWriter) error
}

type PostApiTradingStart200JSONResponse TradingStatusResponse

func (response PostApiTradingStart200JSONResponse) VisitPostApiTradingStartResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostApiTradingStart500JSONResponse TradingStatusResponse

func (response PostApiTradingStart500JSONResponse) VisitPostApiTradingStartResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostApiTradingStart503JSONResponse struct{ ServiceUnavailableJSONResponse }

func (response PostApiTradingStart503JSONResponse) VisitPostApiTradingStartResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type GetApiTradingStatusRequestObject struct {
}

type GetApiTradingStatusResponseObject interface {
	VisitGetApiTradingStatusResponse(w http.ResponseWriter) error
}

type GetApiTradingStatus200JSONResponse TradingStatusResponse

func (response GetApiTradingStatus200JSONResponse) VisitGetApiTradingStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetApiTradingStatus503JSONResponse struct{ ServiceUnavailableJSONResponse }

func (response GetApiTradingStatus503JSONResponse) VisitGetApiTradingStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type PostApiTradingStopRequestObject struct {
}

type PostApiTradingStopResponseObject interface {
	VisitPostApiTradingStopResponse(w http.ResponseWriter) error
}

type PostApiTradingStop200JSONResponse TradingStatusResponse

func (response PostApiTradingStop200JSONResponse) VisitPostApiTradingStopResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostApiTradingStop500JSONResponse TradingStatusResponse

func (response PostApiTradingStop500JSONResponse) VisitPostApiTradingStopResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostApiTradingStop503JSONResponse struct{ ServiceUnavailableJSONResponse }

func (response PostApiTradingStop503JSONResponse) VisitPostApiTradingStopResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse HealthResponse

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// 残高取得
	// (GET /api/balance)
	GetApiBalance(ctx context.Context, request GetApiBalanceRequestObject) (GetApiBalanceResponseObject, error)
	// 現在の設定を取得
	// (GET /api/config)
	GetApiConfig(ctx context.Context, request GetApiConfigRequestObject) (GetApiConfigResponseObject, error)
	// 設定を更新
	// (POST /api/config)
	PostApiConfig(ctx context.Context, request PostApiConfigRequestObject) (PostApiConfigResponseObject, error)
	// ログの取得
	// (GET /api/logs)
	GetApiLogs(ctx context.Context, request GetApiLogsRequestObject) (GetApiLogsResponseObject, error)
	// 注文履歴の取得
	// (GET /api/orders)
	GetApiOrders(ctx context.Context, request GetApiOrdersRequestObject) (GetApiOrdersResponseObject, error)
	// パフォーマンス指標の取得
	// (GET /api/performance)
	GetApiPerformance(ctx context.Context, request GetApiPerformanceRequestObject) (GetApiPerformanceResponseObject, error)
	// システム状態の取得
	// (GET /api/status)
	GetApiStatus(ctx context.Context, request GetApiStatusRequestObject) (GetApiStatusResponseObject, error)
	// 戦略状態のリセット
	// (POST /api/strategy/reset)
	PostApiStrategyReset(ctx context.Context, request PostApiStrategyResetRequestObject) (PostApiStrategyResetResponseObject, error)
	// 取引履歴の取得
	// (GET /api/trades)
	GetApiTrades(ctx context.Context, request GetApiTradesRequestObject) (GetApiTradesResponseObject, error)
	// 取引開始
	// (POST /api/trading/start)
	PostApiTradingStart(ctx context.Context, request PostApiTradingStartRequestObject) (PostApiTradingStartResponseObject, error)
	// 取引状態の取得
	// (GET /api/trading/status)
	GetApiTradingStatus(ctx context.Context, request GetApiTradingStatusRequestObject) (GetApiTradingStatusResponseObject, error)
	// 取引停止
	// (POST /api/trading/stop)
	PostApiTradingStop(ctx context.Context, request PostApiTradingStopRequestObject) (PostApiTradingStopResponseObject, error)
	// ヘルスチェック
	// (GET /health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetApiBalance operation middleware
func (sh *strictHandler) GetApiBalance(w http.ResponseWriter, r *http.Request) {
	var request GetApiBalanceRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiBalance(ctx, request.(GetApiBalanceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiBalance")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetApiBalanceResponseObject); ok {
		if err := validResponse.VisitGetApiBalanceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetApiConfig operation middleware
func (sh *strictHandler) GetApiConfig(w http.ResponseWriter, r *http.Request) {
	var request GetApiConfigRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiConfig(ctx, request.(GetApiConfigRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiConfig")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetApiConfigResponseObject); ok {
		if err := validResponse.VisitGetApiConfigResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostApiConfig operation middleware
func (sh *strictHandler) PostApiConfig(w http.ResponseWriter, r *http.Request) {
	var request PostApiConfigRequestObject

	var body PostApiConfigJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostApiConfig(ctx, request.(PostApiConfigRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostApiConfig")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostApiConfigResponseObject); ok {
		if err := validResponse.VisitPostApiConfigResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetApiLogs operation middleware
func (sh *strictHandler) GetApiLogs(w http.ResponseWriter, r *http.Request, params GetApiLogsParams) {
	var request GetApiLogsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiLogs(ctx, request.(GetApiLogsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiLogs")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetApiLogsResponseObject); ok {
		if err := validResponse.VisitGetApiLogsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetApiOrders operation middleware
func (sh *strictHandler) GetApiOrders(w http.ResponseWriter, r *http.Request, params GetApiOrdersParams) {
	var request GetApiOrdersRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiOrders(ctx, request.(GetApiOrdersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiOrders")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetApiOrdersResponseObject); ok {
		if err := validResponse.VisitGetApiOrdersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetApiPerformance operation middleware
func (sh *strictHandler) GetApiPerformance(w http.ResponseWriter, r *http.Request) {
	var request GetApiPerformanceRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiPerformance(ctx, request.(GetApiPerformanceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiPerformance")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetApiPerformanceResponseObject); ok {
		if err := validResponse.VisitGetApiPerformanceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetApiStatus operation middleware
func (sh *strictHandler) GetApiStatus(w http.ResponseWriter, r *http.Request, params GetApiStatusParams) {
	var request GetApiStatusRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiStatus(ctx, request.(GetApiStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiStatus")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetApiStatusResponseObject); ok {
		if err := validResponse.VisitGetApiStatusResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostApiStrategyReset operation middleware
func (sh *strictHandler) PostApiStrategyReset(w http.ResponseWriter, r *http.Request) {
	var request PostApiStrategyResetRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostApiStrategyReset(ctx, request.(PostApiStrategyResetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostApiStrategyReset")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostApiStrategyResetResponseObject); ok {
		if err := validResponse.VisitPostApiStrategyResetResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetApiTrades operation middleware
func (sh *strictHandler) GetApiTrades(w http.ResponseWriter, r *http.Request, params GetApiTradesParams) {
	var request GetApiTradesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiTrades(ctx, request.(GetApiTradesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiTrades")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetApiTradesResponseObject); ok {
		if err := validResponse.VisitGetApiTradesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostApiTradingStart operation middleware
func (sh *strictHandler) PostApiTradingStart(w http.ResponseWriter, r *http.Request) {
	var request PostApiTradingStartRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostApiTradingStart(ctx, request.(PostApiTradingStartRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostApiTradingStart")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostApiTradingStartResponseObject); ok {
		if err := validResponse.VisitPostApiTradingStartResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetApiTradingStatus operation middleware
func (sh *strictHandler) GetApiTradingStatus(w http.ResponseWriter, r *http.Request) {
	var request GetApiTradingStatusRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiTradingStatus(ctx, request.(GetApiTradingStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiTradingStatus")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetApiTradingStatusResponseObject); ok {
		if err := validResponse.VisitGetApiTradingStatusResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostApiTradingStop operation middleware
func (sh *strictHandler) PostApiTradingStop(w http.ResponseWriter, r *http.Request) {
	var request PostApiTradingStopRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostApiTradingStop(ctx, request.(PostApiTradingStopRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostApiTradingStop")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostApiTradingStopResponseObject); ok {
		if err := validResponse.VisitPostApiTradingStopResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
